### ISSUE TITLE
불편해요. 불편해요. 불편해요.

### ISSUE THREAD

**Issue by softpeanut** [baekteun/Portfoilo#16]
### Describe

아이폰에 있는 앱을 누르면 아래 보이는 화면처럼 맞춰집니다.
근데 위에 공백이 없는게 너무 불편해요.
고쳐줘요 찡찡

<img width="600" alt="image" src="https://user-images.githubusercontent.com/80632060/219048314-5ef87bb7-31d9-45ae-a606-a482e397bcc8.png">

**Comment by baekteun** [comment]
바로 갈깁니다

**Comment by softpeanut** [comment]
역시 좋아요

**Comment by baekteun** [comment]
#20 해당 PR에 반영되었습니당
